apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ddcc-gateway
  name: ddcc-gateway
  namespace: default
spec:
  selector:
    matchLabels:
      app: ddcc-gateway
  template:
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "1"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-federation.jks: gateway/data/federation
        vault.hashicorp.com/agent-inject-secret-gwenv: gateway/data/mtls
        vault.hashicorp.com/agent-inject-secret-keystore.jks: gateway/data/mtls
        vault.hashicorp.com/agent-inject-secret-postgres: postgres-db/data/gateway
        vault.hashicorp.com/agent-inject-secret-trustAnchor.jks: gateway/data/trustAnchor
        vault.hashicorp.com/agent-inject-secret-truststore.jks: gateway/data/mtls
        vault.hashicorp.com/agent-inject-template-federation.jks: |
          {{- with secret "gateway/data/federation" -}}
            {{base64Decode .Data.data.keystore}}
          {{- end -}}
        vault.hashicorp.com/agent-inject-template-gwenv: | 
          {{- with secret "gateway/data/mtls" -}}
            export SERVER_SSL_KEY_PASSWORD={{ .Data.data.keypassword}}
            export SERVER_SSL_KEY_STORE_PASSWORD={{ .Data.data.keystorepassword}}
            export SERVER_SSL_TRUST_STORE_PASSWORD={{ .Data.data.truststorepassword}}
          {{- end -}}
          {{printf "%s" "\n"}}
          {{- with secret "gateway/data/trustAnchor" -}}
            export DGC_TRUSTANCHOR_KEYSTOREPASS={{ .Data.data.keyStorePw}}
          {{- end -}}
          {{printf "%s" "\n"}}
          {{- with secret "gateway/data/federation" -}}
            export DGC_FEDERATION_KEYSTOREPASSWORD={{ .Data.data.keystorepassword}}
            export DGC_FEDERATION_KEYSTOREKEYPASSWORD={{ .Data.data.keystorekeypassword}}
          {{- end -}}\n"
        vault.hashicorp.com/agent-inject-template-keystore.jks: |
          {{- with secret "gateway/data/mtls" -}}
            {{base64Decode .Data.data.keystore}}
          {{- end -}}
        vault.hashicorp.com/agent-inject-template-postgres: |
          {{- with secret "postgres-db/data/gateway" -}}
            export POSTGRES_DB={{ .Data.data.POSTGRES_DB }}
            export SPRING_DATASOURCE_USERNAME={{ .Data.data.POSTGRES_USER }}
            export SPRING_DATASOURCE_PASSWORD={{ .Data.data.POSTGRES_PASSWORD }}
            export SPRING_DATASOURCE_URL=jdbc:postgresql://${DDCC_GATEWAY_POSTGRES_SERVICE_HOST}:${DDCC_GATEWAY_POSTGRES_SERVICE_PORT}/{{ .Data.data.POSTGRESQL_DATABASE }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-template-trustAnchor.jks: | 
          {{- with secret "gateway/data/trustAnchor" -}}
           {{base64Decode .Data.data.keystore}}
          {{- end -}}
        vault.hashicorp.com/agent-inject-template-truststore.jks: |
          {{- with secret "gateway/data/mtls" -}}
            {{base64Decode .Data.data.truststore}}
          {{- end -}}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: gateway
      creationTimestamp: null
      labels:
        app: ddcc-gateway
    spec:
      containers:
      - args:
        - -c
        - . /vault/secrets/postgres && . /vault/secrets/gwenv &&  java $JAVA_OPTS
          -Djava.security.egd=file:/dev/./urandom -jar /ddccg.jar run
        command:
        - /bin/sh
        env:
        - name: SERVER_SSL_KEY_STORE
          value: /vault/secrets/keystore.jks
        - name: SERVER_SSL_TRUST_STORE
          value: /vault/secrets/truststore.jks
        - name: DGC_TRUSTANCHOR_KEYSTOREPATH
          value: /vault/secrets/trustanchor.jks
        - name: DGC_FEDERATION_KEYSTOREPATH
          value: /vault/secrets/federation.jks
        - name: SPRING_PROFILES_ACTIVE
          value: mtls,log2console
        - name: SPRING_DATASOURCE_DRIVERCLASSNAME
          value: org.postgresql.Driver
        - name: SPRING_JPA_DATABASEPLATFORM
          value: org.hibernate.dialect.PostgreSQLDialect
        - name: HAPI_FHIR_ALLOW_EXTERNAL_REFERENCES
          value: "true"
        - name: SERVER_SSL_KEY_ALIAS
          value: server
        - name: SPRING_DATASOURCE_JNDI_NAME
          value: "false"
        - name: DGC_TRUSTANCHOR_CERTIFICATEALIAS
          value: ta
        image: ghcr.io/worldhealthorganization/ddcc-gateway/ddcc-gateway:1.3.0-3b43b3c
        imagePullPolicy: IfNotPresent
        name: ddcc-gateway
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
      imagePullSecrets:
      - name: githubpullsecret
      serviceAccount: ddcc-gateway
      serviceAccountName: ddcc-gateway
